### ISSUE TITLE
Repeat loop - allow looping over custom values

### ISSUE THREAD

**Issue by mcimbora** [radargun/radargun#252]
Thanks @alanfx for proposal. Currently repeat loop exposes its state only via repeat.counter variable. It would be nice if repeat loop enabled us to loop over pre-defined list of custom values & use their reference inside the loop.

e.g.
`<repeat vars="size:[1, 2, 5, 111]">
   <stage1 value-size="${repeat.size}"/>
</repeat>`

Multiple properties could be defined if we could enforce property lists to be of the same sizes for all defined properties.

`<repeat vars="size:[1, 2, 5, 111];count:[3, 10, 50, 68]">
   <stage1 value-size="${repeat.size}" count="${repeat.count}"/>
</repeat>`

It looks like only one pattern could be used at the same time (i.e. from-to/times vs var).

@alanfx @rvansa Wdyt?

**Comment by rvansa** [comment]
@mcimbora Honestly I don't like the property-like syntax too much - generally, I'd like to use structured attribute values as little as possible/practical. What about list access operator and use it along with existing DefineStage?

```
<define var="loop-vars" value="1, 2, 5, 111"/>
<repeat from="0" to="#{ length(${loop.vars}) }">
    <stage foo="#{ ${loop.vars}[${repeat.counter}] }" />
</repeat>
```
If the value should be reused, you can refactor the expression to another `define` element in the loop.

Instead of `#{ length(${loop.vars}) }` we could have `#{ ${loop.vars}.length }` if you're willing to implement the access operator, too.

**Comment by mcimbora** [comment]
@rvansa I agree, this would probably not require too many internal changes & I like reusing what we already have.

**Comment by alanfx** [comment]
@mcimbora and @rvansa, I agree as well.

**Comment by mcimbora** [comment]
Resolved by https://github.com/radargun/radargun/pull/257.
