### ISSUE TITLE
Create JGroups 3.6.6 plugin

### ISSUE THREAD

**Issue by belaban** [radargun/radargun#295]
New plugin to test JGroups 3.6.6

**Comment by rvansa** [comment]
I was actually planning to drop JGroups plugins completely, since these are rather mocks than really implementing the cache API. They should eventually get back in as we're interested in JGroups performance but in very different shape; a new Messaging [trait](https://github.com/radargun/radargun/wiki/Design-Documentation#plugins-service-and-traits) should be defined that will focus on RPC/messages, and could be implemented by JGroups, JMS and others.

**Comment by belaban** [comment]
I would only drop this *after* Messaging traits have been implemented; meanwhile this is a very useful feature to get a baseline against which to measure Infinispan's perf...

**Comment by rvansa** [comment]
OK, fair enough.

Would you be interested in development of this trait? I guess that you are interested in comparisons with other messaging frameworks.

**Comment by belaban** [comment]
Sorry, no time

**Comment by belaban** [comment]
This will be a new plugin, not extending another `JGroupsService`. It will also contain a few changes, such as
* GET only sent to a single dest (saving us a round-trip)
* PUT sent to primary etc

**Comment by belaban** [comment]
Submitted PR: https://github.com/radargun/radargun/pull/306

**Comment by mcimbora** [comment]
Closing. Created new issue for messaging trait implementation https://github.com/radargun/radargun/issues/323.
