### ISSUE TITLE
Investigate new classpath scanner

### ISSUE THREAD

**Issue by alanfx** [radargun/radargun#373]
The current `ClasspathScanner` class uses reflection which causes static initializers to be executed. This is not a huge issue when generating the schema during the build, but is a bigger issue when executing a benchmark and trying to determine which exceptions are important. Investigate using [https://github.com/lukehutch/fast-classpath-scanner](https://github.com/lukehutch/fast-classpath-scanner) instead, which parses class files directly.

**Comment by rvansa** [comment]
Hmm, interesting. I have already tried to use Javassist to avoid the static intializers ([see here](https://github.com/rvansa/radargun/commit/570bf8ab214cdb681b261fef072bea29f349bffb) ) though I instantiate the class anyway because if I inspect JAR file without its dependencies, I could get errors because the superclass is not to be found.

**Comment by alanfx** [comment]
https://github.com/radargun/radargun/pull/381

**Comment by alanfx** [comment]
Resolving this based on the two PRs above

**Comment by rvansa** [comment]
@alanfx FYI, https://github.com/lukehutch/fast-classpath-scanner/issues/69 has swiftly implemented the API we were looking for.

**Comment by alanfx** [comment]
@rvansa Nice, I also entered https://github.com/lukehutch/fast-classpath-scanner/issues/70 which is also fixed!

**Comment by alanfx** [comment]
Getting the annotations with the new APIs is working for me:

```
      List<String> matches = scanResults.getClassNameToClassInfo().values().stream()
            .filter(ci -> ci.hasAnnotation(annotationClass.getName())).map(ClassInfo::getClassName)
            .collect(Collectors.toList());
```

Getting the super/subclasses is not though.

```
         assignableFrom = scanResults.getClassNameToClassInfo().values().stream()
               .filter(ci -> ci.hasSuperclass(superClass.getName())).map(ClassInfo::getClassName)
               .collect(Collectors.toList());
```

With this code, `assignableFrom.size()` is always zero.

**Comment by lukehutch** [comment]
Hi guys, thanks for the bug reports. I'll try to get these last few things fixed up too.

(FYI FastClasspathScanner does not load the classes, so static initializers are not run unless you use "Mechanism 1" (adding a MatchProcessor before scanning), but I think that was your point in the earlier comment.)

Re. this last comment: superclasses will not be returned if they are not in a whitelisted package, however to minimize confusion, I'm considering changing this so that as long as classes are directly referenced by a class in a whitelisted package, they are still returned.

**Comment by alanfx** [comment]
OK, with version 1.93.1 I can get the subclasses and interface implementors using this code:

```
         assignableFrom = scanResults.getClassNameToClassInfo().values().stream()
               .filter(ci -> ci.hasSuperclass(superClass.getName()) || ci.implementsInterface(superClass.getName()))
               .map(ClassInfo::getClassName).collect(Collectors.toList());
```

Thanks a lot for the quick response, Luke!

**Comment by lukehutch** [comment]
You're welcome, glad it's working for you now!
