### ISSUE TITLE
Broken report stylesheet

### ISSUE THREAD

**Issue by vjuranek** [radargun/radargun#500]
Report style sheet is broken, it shows only black screen with Close (see attached screenshot). Disabling style sheet shows the content. It seems to happen only when statistics is gathered.
![rg_report](https://user-images.githubusercontent.com/494573/33421761-723ed818-d5b3-11e7-868c-6da42c200793.png)

**Comment by vjuranek** [comment]
It's caused by `.glasspanel` in `style.css`. Observation: when I download report on my local computer, everything works.

**Comment by rvansa** [comment]
Your browser does not support stylesheets in the internetz?

**Comment by alanfx** [comment]
Hey @vjuranek, can you try bringing up a Web Inspector or JavaScript Console in your browser when you load this page to see if any of the debug messages give you a clue what is happening?

**Comment by alanfx** [comment]
FWIW, I see a ton of these errors when I load [test_storage-test.html](https://jdg-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jdg-perf-offheap-get/8/artifact/results/html/test_storage-test.html):

`[Error] Blocked script execution in 'https://jdg-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jdg-perf-offheap-get/8/artifact/results/html/test_storage-test.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set. (test_storage-test.html, line 1548)`

This SO question blames Jenkins for this...

https://stackoverflow.com/questions/34315723/blocked-script-execution-in-url-because-the-documents-frame-is-sandboxed-and#34372607

**Comment by vjuranek** [comment]
@rvansa for security reasons my browser allows only `127.0.0.1`

@alanfx hm, of course I did check it, but my browsers only says something like "page setup has blocked loading of the resource self", which I don't understand:-) Anyway, what you find out make sense, will look on it. Thanks!

**Comment by vjuranek** [comment]
turning off `hudson.model.DirectoryBrowserSupport.CSP` doesn't seems to help. I set it up via groovy console in Jenkins and the result is still same.

**Comment by vjuranek** [comment]
ok, probably cached in the browser, So it works! Thanks @alanfx !
Closing.

**Comment by alanfx** [comment]
@vjuranek Sweet! Glad it worked for you!
